#!/usr/bin/env bash
# ♾️ Dispatch standalone caller
# Call me like dispatch myscript myfunction
# TODO, not operational yet, this is still an example

export g_dispatch_project_name=DISPATCH

# Source lib
: "${gs_root_path:=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")}"
source "$gs_root_path"/script/lib_dispatch.sh

script_path="$gs_root_path"/script


declare -A g_dispatch_d_cmd=(
  # Utils
  [example]="$script_path/example.sh"
  [util]="$script_path/util.sh"
)

register_subcommand_from_gd_cmd

__default(){
  print_usage_main --help
}

# If executed and not sourced, print self doc
if [[ -v BASH_SOURCE ]] && (( ${#BASH_SOURCE[@]} > 0 )) && [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  dispatch "$@"; exit $?;
fi
