---
# Launch unit test suite with bash
# yamllint disable rule:line-length

name: Unit

# yamllint disable-line rule:truthy
on: [push, pull_request, workflow_dispatch]

jobs:
  unit:
    name: "Unit: ${{ matrix.os }}"
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Run Unit
        run: |
          # Install bash on mac
          # From: https://stackoverflow.com/questions/69211983
          if [[ "$MATRIX_OS" == 'macos-latest' ]]; then
            echo "\n\n==> Instaling Bash"
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            brew update

            brew install bash
            brew install gnu-sed

            echo "/usr/local/bin" >> $GITHUB_PATH
            echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          fi

          echo "\n\n==> Bash Version"
          bash --version

          echo "\n\n==> Environment"
          env

          echo "\n\n==> Hi"
          ./dispatch util hi

          echo "\n\n==> Unit"
          ./dispatch util unit_test
        env:
          MATRIX_OS: ${{ matrix.os }}
        shell: bash
